#!/usr/bin/env python3
"""Build the Universal Data Suite test report (.xlsx) from the headless test
harness results (test_files/output/test_results.json).

Sheets:
  1. Summary          - run metadata, pass/fail totals, test method.
  2. Requirements     - S.No, Requirement, Functionality, Description
                        (the main features across all versions + the problem
                        each solves).
  3. Test Cases       - S.No, Test ID, ICD / Dataset, Feature Area,
                        Problem Tested, Status, Evidence (driven by real
                        harness results).
  4. ICD Dataset      - the sample ICDs used and what each exercises.
"""
import json, os, datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(HERE, 'output', 'test_results.json')
OUT = os.path.join(HERE, 'output', 'Universal_Data_Suite_Test_Report.xlsx')

# ---- palette -------------------------------------------------------------
NAVY   = '1F3864'
BLUE   = '2E5496'
LIGHT  = 'D9E1F2'
GREEN  = 'C6EFCE'
GREENF = '006100'
RED    = 'FFC7CE'
REDF   = '9C0006'
GREY   = 'F2F2F2'
WHITE  = 'FFFFFF'

THIN = Side(style='thin', color='BFBFBF')
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def hdr_fill():
    return PatternFill('solid', fgColor=NAVY)


def style_header(ws, row, ncols):
    for c in range(1, ncols + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = Font(bold=True, color=WHITE, size=11)
        cell.fill = hdr_fill()
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell.border = BORDER


def put_row(ws, row, values, wrap_cols=(), center_cols=(), zebra=False):
    for i, v in enumerate(values, start=1):
        cell = ws.cell(row=row, column=i, value=v)
        cell.border = BORDER
        cell.alignment = Alignment(
            horizontal='center' if i in center_cols else 'left',
            vertical='top', wrap_text=(i in wrap_cols))
        cell.font = Font(size=10)
        if zebra and row % 2 == 0:
            cell.fill = PatternFill('solid', fgColor=GREY)


def set_widths(ws, widths):
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w


# ---- load results --------------------------------------------------------
with open(RESULTS, 'r', encoding='utf-8') as f:
    data = json.load(f)
results = data['results']
total, passed, failed = data['total'], data['passed'], data['failed']

wb = Workbook()

# ========================================================== 1) Summary
ws = wb.active
ws.title = 'Summary'
ws.sheet_view.showGridLines = False
ws.merge_cells('A1:D1')
t = ws['A1']
t.value = 'Universal Data Suite - Software Test Report'
t.font = Font(bold=True, size=16, color=NAVY)
t.alignment = Alignment(horizontal='left', vertical='center')
ws.row_dimensions[1].height = 26

ws.merge_cells('A2:D2')
s = ws['A2']
s.value = ('Two desktop apps from one shared core: Universal Wireshark Log Reader '
           '(decode pcap/live UDP-TCP into engineering values) and Universal Data '
           'Simulator (transmit HEX / NMEA over UDP, TCP, serial).')
s.font = Font(size=10, italic=True, color='404040')
s.alignment = Alignment(horizontal='left', vertical='center', wrap_text=True)
ws.row_dimensions[2].height = 30

meta = [
    ('Report date', datetime.date.today().isoformat()),
    ('Branch', 'universal-data-suite'),
    ('Build', 'Qt 5.10.1 / mingw53_32 - both apps compile 0 errors'),
    ('Test method', 'Automated headless harness (tests/run_tests.pro) exercising the '
                    'REAL data-path code of both apps - shared ICD importer, codecs, '
                    'validators, the simulator PayloadBuilder (encode) and the reader '
                    'ExtractionEngine (decode), plus the PcapWriter -> PcapFileReader -> '
                    'UdpPacketParser capture round-trip. No mocks.'),
    ('ICD dataset', '8 sample ICD .docx files generated by make_test_icds.py'),
    ('Total checks', total),
    ('Passed', passed),
    ('Failed', failed),
    ('Result', 'ALL PASSED' if failed == 0 else f'{failed} FAILED'),
]
r = 4
for k, v in meta:
    kc = ws.cell(row=r, column=1, value=k)
    kc.font = Font(bold=True, size=10, color=NAVY)
    kc.alignment = Alignment(horizontal='left', vertical='top')
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
    vc = ws.cell(row=r, column=2, value=v)
    vc.alignment = Alignment(horizontal='left', vertical='top', wrap_text=True)
    vc.font = Font(size=10)
    if k in ('Passed', 'Result') and failed == 0:
        vc.font = Font(size=10, bold=True, color=GREENF)
        vc.fill = PatternFill('solid', fgColor=GREEN)
    if k == 'Failed' and failed > 0:
        vc.font = Font(size=10, bold=True, color=REDF)
        vc.fill = PatternFill('solid', fgColor=RED)
    if isinstance(v, str) and len(v) > 90:
        ws.row_dimensions[r].height = 46
    r += 1
set_widths(ws, [16, 30, 30, 30])

# Note row
ws.merge_cells(start_row=r + 1, start_column=1, end_row=r + 1, end_column=4)
note = ws.cell(row=r + 1, column=1,
    value='Note: purely visual / GUI-interaction features (themes, drag-reorder, '
          'tooltips, dialog layouts) are covered by the clean build and code review; '
          'the automated cases below target the functional data path that can be '
          'verified deterministically.')
note.font = Font(size=9, italic=True, color='808080')
note.alignment = Alignment(wrap_text=True, vertical='top')
ws.row_dimensions[r + 1].height = 40

# ========================================================== 2) Requirements
# S.No, Requirement, Functionality, Description (feature + problem solved).
REQUIREMENTS = [
    ('Two-app data suite',
     'One qmake project builds the Reader and the Simulator from a shared core.',
     'Lets one codebase serve both decoding captured/live data and generating test data; '
     'the two apps are each other natural test rig.'),
    ('PCAP / PCAPNG decoding',
     'Reader opens a .pcap/.pcapng file and decodes UDP/TCP payloads into values.',
     'Turns raw Wireshark captures into engineering values without manual byte maths.'),
    ('Live UDP / TCP capture',
     'Reader binds one receiver per connection and decodes datagrams live.',
     'Validates equipment output in real time; traffic from different adapters/ports never mixes.'),
    ('Multi-transport transmit',
     'Simulator transmits user-defined messages over UDP, TCP or serial COM.',
     'Provides a controllable stimulus source to exercise a system under test.'),
    ('ICD .docx import',
     'Reads a Word ICD, extracts every table, auto-detects columns and builds messages.',
     'Removes hours of manual field entry by importing the interface spec directly.'),
    ('ICD continuation merge',
     'Tables that continue a message across a page break are stitched into one message.',
     'Handles real-world ICDs whose messages span multiple tables/pages.'),
    ('All field data types',
     'uchar/char, u/short, u/int, u/long, float, double, bool, string, raw unsigned BE.',
     'Covers every field encoding an ICD is likely to specify.'),
    ('Resolution scaling',
     'Each field carries a resolution (decimal or fraction); value = raw * resolution.',
     'Decodes scaled sensor counts (e.g. 0.0000001 deg) into real units.'),
    ('Wide-field decode (>8 bytes)',
     'Reader decodes integer fields of any width via exact base-256 to base-10.',
     'Supports identifiers/blobs wider than 64 bits that a normal int cannot hold.'),
    ('Encode/decode contract',
     'Simulator encode is the exact inverse of the reader decode (BE default, per-field LE).',
     'Guarantees what the simulator sends is what the reader reads back, byte for byte.'),
    ('Hex value entry',
     'Integer field values accept a 0x hex prefix; a live Hex column shows the wire bytes.',
     'Lets users specify exact bit patterns and see the bytes before sending.'),
    ('Bytes / Words offset unit',
     'Field offsets can be entered/shown in bytes or 16-bit words; storage stays in bytes.',
     'Matches ICDs that address payloads in words without changing the decode engine.'),
    ('Excel field import/export',
     'Field lists round-trip to .xlsx (name, offset, type, length, resolution, value, endianness).',
     'Lets engineers prepare and review field maps in a spreadsheet.'),
    ('JSON message interchange',
     'Whole messages and field lists export/import as JSON, lossless and lenient on load.',
     'Moves a configuration freely between the two apps and across versions.'),
    ('Multi-connection model',
     'Each message binds to a named connection; the Reader/Simulator manage a connection list.',
     'Keeps several endpoints in one session without re-configuring per run.'),
    ('One message to many connections',
     'A message can be ticked to several connections via a checkable dropdown and fans out.',
     'Sends the same stimulus to multiple destinations at once (new in this version).'),
    ('Word-offset save stability',
     'A word offset entered in Configure Fields stays put across save/reopen.',
     'Fixes a defect where word offsets drifted (1,2,3,4 -> 1,1,2,2) on every save.'),
    ('NMEA-0183 build & decode',
     'Builds $talker+formatter,tokens*checksum+CRLF and decodes it back, verifying the XOR.',
     'Supports marine/navigation feeds alongside raw HEX messages.'),
    ('Compare / verify options',
     'Per-message header, terminator, checksum, refresh-rate, endianness, length and id checks.',
     'Flags malformed or out-of-spec traffic during decoding.'),
    ('pcapng export & inspector',
     'Simulator exports sent history to pcapng and shows a Wireshark-style packet inspector.',
     'Captures generated traffic for evidence and offline analysis.'),
    ('Bitfield decoders',
     'Per-bit and conditional (controller-driven) bit decoding of integer fields.',
     'Decodes packed status/flag words into named meanings.'),
    ('Input validation',
     'Every user value is validated; each failure reports a reason AND a solution.',
     'Prevents bad configurations and tells the user exactly how to fix them.'),
    ('Standard folders & autosave',
     'Output/Projects folders under Documents; live + simulator autosave and restore.',
     'Protects work and gives every export a predictable home.'),
    ('Theming & in-app manual',
     'Modern Light / Slate Dark themes and a searchable in-app user manual (F1).',
     'Improves usability and provides built-in guidance.'),
]

ws = wb.create_sheet('Requirements')
ws.sheet_view.showGridLines = False
ws.merge_cells('A1:D1')
h = ws['A1']
h.value = 'Requirements & Functionality - main features and the problem each solves'
h.font = Font(bold=True, size=13, color=NAVY)
ws.row_dimensions[1].height = 22
headers = ['S.No', 'Requirement', 'Functionality', 'Description (problem solved)']
for i, htext in enumerate(headers, start=1):
    ws.cell(row=2, column=i, value=htext)
style_header(ws, 2, 4)
r = 3
for i, (req, func, desc) in enumerate(REQUIREMENTS, start=1):
    put_row(ws, r, [i, req, func, desc], wrap_cols=(2, 3, 4), center_cols=(1,), zebra=True)
    ws.row_dimensions[r].height = 34
    r += 1
set_widths(ws, [6, 26, 52, 60])
ws.freeze_panes = 'A3'
ws.auto_filter.ref = f'A2:D{r-1}'

# ========================================================== 3) Test Cases
ws = wb.create_sheet('Test Cases')
ws.sheet_view.showGridLines = False
ws.merge_cells('A1:G1')
h = ws['A1']
h.value = 'Test Cases - sample ICDs / datasets x the problem tested x result'
h.font = Font(bold=True, size=13, color=NAVY)
ws.row_dimensions[1].height = 22
headers = ['S.No', 'Test ID', 'ICD / Dataset', 'Feature Area', 'Problem Tested', 'Status', 'Evidence']
for i, htext in enumerate(headers, start=1):
    ws.cell(row=2, column=i, value=htext)
style_header(ws, 2, 7)

r = 3
for i, rec in enumerate(results, start=1):
    status = 'Passed' if rec['status'] == 'PASS' else 'Failed'
    put_row(ws, r, [i, rec['id'], rec['icd'], rec['area'], rec['problem'], status, rec['detail']],
            wrap_cols=(3, 5, 7), center_cols=(1, 2, 6))
    sc = ws.cell(row=r, column=6)
    if status == 'Passed':
        sc.fill = PatternFill('solid', fgColor=GREEN)
        sc.font = Font(bold=True, color=GREENF, size=10)
    else:
        sc.fill = PatternFill('solid', fgColor=RED)
        sc.font = Font(bold=True, color=REDF, size=10)
    ws.row_dimensions[r].height = 30
    r += 1
set_widths(ws, [6, 9, 22, 16, 46, 11, 46])
ws.freeze_panes = 'A3'
ws.auto_filter.ref = f'A2:G{r-1}'

# ========================================================== 4) ICD Dataset
ICDS = [
    ('icd_radar_basic.docx', '2 messages (Track + Status) on one port',
     'Multi-message extraction, column auto-detect, encode/decode of common types.'),
    ('icd_all_types.docx', 'One message with all 12 field types',
     'Every data type label is recognised and round-trips through encode/decode.'),
    ('icd_scaled.docx', 'Fields with 0.01, 0.0055 and 1/3 resolutions',
     'Per-field resolution import and value = raw * resolution scaled decode.'),
    ('icd_wide_fields.docx', '12- and 16-byte unsigned fields',
     'Wide (>8 byte) exact decode beyond a 64-bit integer.'),
    ('icd_length_msgid.docx', 'Message-id + data-length framed message',
     'Import of framed messages that carry id and length fields.'),
    ('icd_lenient.docx', 'Rows with a missing key and a duplicate name',
     'Duplicate name renamed _2; rows missing a required key skipped safely.'),
    ('icd_continuation.docx', 'One message split across two tables',
     'Continuation tables auto-merge into a single concatenated message.'),
    ('icd_word_offsets.docx', 'Offsets given in 16-bit words',
     'Word-addressed import and stable Bytes/Words offset conversion.'),
]
ws = wb.create_sheet('ICD Dataset')
ws.sheet_view.showGridLines = False
ws.merge_cells('A1:C1')
h = ws['A1']
h.value = 'Sample ICD dataset used for testing (test_files/icd_*.docx)'
h.font = Font(bold=True, size=13, color=NAVY)
ws.row_dimensions[1].height = 22
for i, htext in enumerate(['ICD File', 'Contents', 'Feature(s) Exercised'], start=1):
    ws.cell(row=2, column=i, value=htext)
style_header(ws, 2, 3)
r = 3
for name, contents, feats in ICDS:
    put_row(ws, r, [name, contents, feats], wrap_cols=(2, 3), zebra=True)
    ws.row_dimensions[r].height = 30
    r += 1
set_widths(ws, [26, 40, 60])
ws.freeze_panes = 'A3'

wb.save(OUT)
print('wrote', OUT)
print(f'{passed}/{total} checks passed; {len(REQUIREMENTS)} requirements; {len(results)} test cases')
