# Universal Data Simulator (sender) — one of the two apps in the suite.
greaterThan(QT_MAJOR_VERSION, 5) {
    CONFIG += c++17
} else {
    CONFIG += c++11
}

TARGET = UniversalDataSimulator
TEMPLATE = app

# org/app = "UniversalDataSimulator" (own QSettings/AppData tree) — see sources/main.cpp.

include(../shared/shared.pri)

INCLUDEPATH += $$PWD/headers

# Excel (.xlsx) import/export — vendored QXlsx (MIT). Now linked into BOTH apps
# so the shared ExcelFieldCodec compiles here too (the .pri self-locates).
QXLSX_PARENTPATH = $$PWD/../third_party/QXlsx/
QXLSX_HEADERPATH = $$PWD/../third_party/QXlsx/header/
QXLSX_SOURCEPATH = $$PWD/../third_party/QXlsx/source/
include(../third_party/QXlsx/QXlsx.pri)

SOURCES += $$files($$PWD/sources/*.cpp)
HEADERS += $$files($$PWD/headers/*.h)
FORMS   += $$files($$PWD/forms/*.ui)

# Embedded searchable user manual (HTML + screenshots), generated by docs/make_manuals.py.
RESOURCES += $$PWD/simulator_manual.qrc
